import io
from typing import List, Dict
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch


class ReportService:
    def generate_pdf_report(
        self,
        candidate_name: str,
        round_type: str,
        question_count: int,
        average_confidence: int,
        strongest_skills: List[str],
        major_improvements: List[str],
        interview_summary: str,
        evaluations: List[Dict],
    ) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Heading1"],
            fontSize=24,
            textColor=colors.HexColor("#1a1a2e"),
            spaceAfter=30,
            alignment=1,
        )
        heading_style = ParagraphStyle(
            "CustomHeading",
            parent=styles["Heading2"],
            fontSize=14,
            textColor=colors.HexColor("#16213e"),
            spaceAfter=12,
            spaceBefore=16,
        )
        body_style = ParagraphStyle(
            "CustomBody",
            parent=styles["BodyText"],
            fontSize=10,
            leading=14,
            spaceAfter=8,
        )

        story = []

        story.append(Paragraph("MockWise Interview Report", title_style))
        story.append(Spacer(1, 0.2 * inch))

        meta_data = [
            ["Candidate Name:", candidate_name],
            ["Interview Round:", round_type.title()],
            ["Questions Answered:", str(question_count)],
            ["Average Confidence:", f"{average_confidence}%"],
        ]
        meta_table = Table(meta_data, colWidths=[2.2 * inch, 3.5 * inch])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f0f0")),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
            ("ALIGN", (0, 0), (0, -1), "LEFT"),
            ("ALIGN", (1, 0), (1, -1), "LEFT"),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 0.2 * inch))

        story.append(Paragraph("Executive Summary", heading_style))
        story.append(Paragraph(interview_summary, body_style))
        story.append(Spacer(1, 0.1 * inch))

        story.append(Paragraph("Strongest Skills", heading_style))
        for skill in strongest_skills:
            story.append(Paragraph(f"• {skill}", body_style))
        story.append(Spacer(1, 0.1 * inch))

        story.append(Paragraph("Major Improvements", heading_style))
        for improvement in major_improvements:
            story.append(Paragraph(f"• {improvement}", body_style))
        story.append(Spacer(1, 0.1 * inch))

        story.append(Paragraph("Question-by-Question Breakdown", heading_style))
        for i, ev in enumerate(evaluations):
            q_text = ev.get("question", f"Question {i+1}")
            conf = ev.get("confidence", 0)
            trans = ev.get("transcription", "")
            strengths = ev.get("strengths", [])
            improvements = ev.get("improvements", [])

            story.append(Paragraph(f"<b>Q{i+1}:</b> {q_text}", body_style))
            story.append(Paragraph(f"<b>Confidence:</b> {conf}%", body_style))
            if trans:
                story.append(Paragraph(f"<b>Transcription:</b> {trans[:200]}{'...' if len(trans) > 200 else ''}", body_style))
            if strengths:
                story.append(Paragraph(f"<b>Strengths:</b> {', '.join(strengths[:3])}", body_style))
            if improvements:
                story.append(Paragraph(f"<b>Improvements:</b> {', '.join(improvements[:3])}", body_style))
            story.append(Spacer(1, 0.05 * inch))

        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph(
            "<i>This report was generated by MockWise AI Interview Platform.</i>",
            ParagraphStyle("Footer", parent=body_style, alignment=1, textColor=colors.grey),
        ))

        doc.build(story)
        buffer.seek(0)
        return buffer.read()


report_service = ReportService()
